### ISSUE TITLE
Order not getting set to completed

### ISSUE THREAD

**Issue by Elenium123** [nartj/sellix-woocommerce#1]
Hello there! I really love the plugin you made and it has helped me a lot, there's just one issue that's kinda crucial to me and my customers, basically whenever they complete the payment in sellix, they get returned to the thank you page and everything is right, but the order status is still on "Pending Payment" Meaning that they won't get their license key until I manually set their order to completed. I hope you receive this message and fix it.

**Comment by nartj** [comment]
Hello, thanks for your interest.
I pushed a fix, I didn't test it, let me know if payment completion is working now.
Have a good day

**Comment by Elenium123** [comment]
Just tested it out, unfortunately it's still not working.

**Comment by nartj** [comment]
Pushed another try, please test it out and let me know.
I don't know your programming level, so please make sure :
- you correctly updated the plugin
- you activated the wordpress debug mode and logging mode

If the problem is not resolved after this second try, please reach out to me by email at nartjeremy@gmail.com, we will set up a call to solve your issue more easily.

Have a good day

**Comment by nartj** [comment]
By "correctly updated the plugin", I mean, knowing I didn't released a new version (and won't until the fix is validated), you have to manually download the repo, make it a zip archive, and upload it to your server.

**Comment by Elenium123** [comment]
Just tested it out again and it still doesn't seem to be working, i've updated it by disabling and removing the old one and uploading the new one, debug and logging mode aren't activated as i don't really know how to correctly activate them. And I can't get in a call sadly.

**Comment by nartj** [comment]
Without any further investigation (logs files for example), I'm affraid I can't do anything more to help you, as this piece of code is currently working on another project I have.
If you have teamspeak, I can put a few hours to help you out.
(Set debug mode and log mode : https://doortoonline.com/how-to-enable-wordpress-logs-and-debug-mode-for/)

**Comment by Elenium123** [comment]
I will enable logs and debug mode now and try again.

**Comment by nartj** [comment]
Logs and debug mode won't make it work, but it is necessary to find out the origin of the problem. You have to update the code to add logs at key moments, in order to check everything is alright.
Currently, there is not much logs in the code.

**Comment by Elenium123** [comment]
I see, i'm not really a developer so i'm not sure how to update the code to add logs, is there anything else we can do?

**Comment by nartj** [comment]
Yep. Send me a mail and set up a call to clarify all that.

**Comment by Elenium123** [comment]
Hmm, like I said i can't get in a call :/

**Comment by Elenium123** [comment]
Also, i'm pretty sure this issue also applies to all other order status changing stuff, i'm thinking it could be from the webhooks that sellix is sending, like the partial btc payment which should put the order on hold etc.

**Comment by nartj** [comment]
Probably yes.
I added some error logs, please update the plugin, make sure logs are activated, test a payment and send me the log file there.

**Comment by Elenium123** [comment]
Great! Give me some time please.

**Comment by Elenium123** [comment]
Ok so i just ran the debugger and logger mode and made a new order, i went to the log files but the stuff in it isn't relevant to this plugin.

**Comment by Elenium123** [comment]
[debug.log](https://github.com/nartj/sellix-woocommerce/files/6245488/debug.log)

**Comment by nartj** [comment]
Again, it is difficult to help you without further investigations. If the webhook is effectively called by sellix, then you could see logs in your logfile.
Indeed, there is no log in the file attached. That means either the webhook is not called, either you failed the log and debug mode setup / the plugin update.

**Comment by Elenium123** [comment]
I just went to the webhook logs in sellix and sent it again, still the same thing. log and debug mode and the plugin update should all be fine

**Comment by Elenium123** [comment]
![image](https://user-images.githubusercontent.com/81765835/113336261-ceaaa280-932e-11eb-95e4-5c4e58fa7e82.png)
I can send this to you if you want

**Comment by Elenium123** [comment]
[php-errors.log](https://github.com/nartj/sellix-woocommerce/files/6245702/php-errors.log)

Here, just used another method of logging

**Comment by nartj** [comment]
I just pushed a new fix, please try it out and let me know.
If still not working, please leave logs there (php-errors.log is alright).

**Comment by Elenium123** [comment]
[php-errors (1).log](https://github.com/nartj/sellix-woocommerce/files/6245830/php-errors.1.log)

**Comment by nartj** [comment]
Pushed again, please try it.

**Comment by nartj** [comment]
And delete the log file in your server before retesting it, in order to delete previous logs.

**Comment by Elenium123** [comment]
[php-errors (2).log](https://github.com/nartj/sellix-woocommerce/files/6245881/php-errors.2.log)

**Comment by nartj** [comment]
Pushed again, please try it.

**Comment by Elenium123** [comment]
[php-errors (3).log](https://github.com/nartj/sellix-woocommerce/files/6245947/php-errors.3.log)

**Comment by nartj** [comment]
Pushed again, please try it.

**Comment by Elenium123** [comment]
It seems to be working perfectly now! I'll double check just incase
Here is the log file if you want
[php-errors (4).log](https://github.com/nartj/sellix-woocommerce/files/6245967/php-errors.4.log)

**Comment by Elenium123** [comment]
Yep it's working now!! I really don't know what to say... Thank you so much!

**Comment by nartj** [comment]
No problem. Please considere starring the project ;) 
Also, I invite you to delete the comments with log files and screenshots as there are potential sensible informations inside it.

**Comment by Elenium123** [comment]
Will do :) If you have a donation link please send it to me. You put so much time in this :D

**Comment by nartj** [comment]
My paypal : aion.rubot@gmail.com
:)

**Comment by Elenium123** [comment]
Sent out, it may not be that much but yeah
Thanks again :) I will close this now
